### PR TITLE
OS Specific Setup

### LINKED ISSUE #2: Echo flag gets printed on macOS
When using the flag ```-e``` for the ```echo``` command on macOS, the flag is not interpreted and gets printed instead.

Linux:
```bash
echo -e "Linux\nOutput"
```
outputs
```
Linux
Output
```

macOS:
```bash
echo -e "macOS\nOutput"
```
outputs
```
-e macOS
Output
```

### PR DESCRIPTION
**Pull request by rcopstein**
Added a check for the running OS, allowing for OS-specific code to be run at the start of the execution.
Created an alias for "echo" to run with the "-e" flag on Linux.
Resolves #2

### CODE REVIEW

**Comment by Taeluf** [comment]
The alias breaks the colorization, and I'm not sure why. Trying to figure that out.

I'm also considering skipping the alias & creating a `msg` function. Then the `msg` function could check if it's Linux or Mac & call the appropriate function.

Aliasing as a setup step does seem like a cleaner solution, though.

**Comment by Taeluf** [comment]
Alias does not appear to be recommended for portable scripts:
- https://unix.stackexchange.com/questions/1496/why-doesnt-my-bash-script-recognize-aliases
- https://askubuntu.com/questions/98782/how-to-run-an-alias-in-a-shell-script

So I'm going to go the route of replacing echo with "msg". Something I was considering anyway, because down the line that might allow for more configurability or something.

**Comment by rcopstein** [comment]
The colorization not working might have something to do with the -e flag preventing the proper evaluation of the color escape codes on linux. As for the usage of a "msg" function, sure, that should work as well. It gives you room to add parameters of your own too.

I would only be careful with how you are checking for the OS. I'm not sure it would be interesting to call ```uname``` every time you want to print something to the screen. My suggestion would to have a file for each OS and, during the OS-specific setup, calling ```. $dir/core/os-specific-file-here.sh```. That way the rest of your code can be left unaware of implementation details and always call the correct function with minimal overhead.

**Comment by Taeluf** [comment]
I did update using an `msg` function & replaced all the `echo -e`, but left regular `echo`. When I tried replacing every `echo`... some things broke, so I thought it safer not to do it everywhere for now.

I kept your version of calling the os setup at the beginning of `bent.sh`, &  modified it to be:
```bash
if [ "$(uname)" == "Darwin" ]; then
    OS="MAC"
    # If necessary, call for macOS 
    # specific initialization code

elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    OS="LINUX"
else
    OS="OTHER"
fi

msg(){
    if [[ $OS == "MAC" ]]; then
        echo "$1" "$2" "$3"
    else 
        echo -e "$1" "$2" "$3"
    fi
}
```

This way `uname` is being called just once. I figured the `msg` function belonged in the `os.sh` file, since it is aware & I'm not sure how to get around that.

**Comment by Taeluf** [comment]
& in case you wondered, I wrote it like `echo "$1" "$2" "$3"` because I'm using `echo -n` in a couple places, so the message was arg2 & I figured... maybe there'll be a third argument sometime...

Hopefully the extra args don't cause an error on mac! Let me know if the colors stopped working or anything broke.

I also changed up the directory structure (had been putting that off).

**Comment by Taeluf** [comment]
(moved my replies to the issue)

**Pull request closed without merging**
